# Generated by Django 5.2 on 2025-06-16 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
