# Generated by Django 5.2 on 2025-08-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_use_bing_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='automatic_background',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_nasa_apod_background',
            field=models.BooleanField(default=False),
        ),
    ]
