# Generated by Django 5.2 on 2025-08-21 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_automatic_background_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_nasa_apod_background',
            new_name='use_nasa_apod_background',
        ),
    ]
