# Generated by Django 5.2 on 2025-08-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_user_nasa_apod_background_profile_use_nasa_apod_background'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='use_bing_background',
            new_name='bing_background',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='use_nasa_apod_background',
            new_name='nasa_apod_background',
        ),
    ]
