# Generated by Django 5.2 on 2025-11-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_use_bing_background_profile_bing_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='claude_api_key_enc',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gemini_api_key_enc',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='openai_api_key_enc',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
