# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_profile_claude_api_key_enc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="openai_chatgpt_token_enc",
            field=models.BinaryField(blank=True, editable=False, null=True),
        ),
    ]
