# Generated by Django 5.2 on 2026-06-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_openai_chatgpt_token_enc'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_dimming',
            field=models.PositiveSmallIntegerField(default=55),
        ),
    ]
