# Generated by Django 5.2 on 2026-07-16 09:21

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_to_date_filter_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(db_default='Europe/Prague', default='Europe/Prague', max_length=64, validators=[users.models.validate_iana_timezone]),
        ),
    ]
