# Generated by Django 5.2 on 2026-07-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profile_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ai_features_enabled',
            field=models.BooleanField(default=False, help_text='Allow this account to use Insights and configure AI provider credentials.', verbose_name='AI features'),
        ),
    ]
