# Generated by Django 5.2 on 2026-09-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_profile_ai_features_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='typesafe_api_key_enc',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
