"""
Django settings for AutumnWeb project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()

# Load env vars from .env if present (prefer BASE_DIR/.env).
env_file = BASE_DIR / ".env"
if env_file.exists():
    environ.Env.read_env(env_file=str(env_file), overwrite=True)
else:
    environ.Env.read_env(overwrite=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

# NASA API Key (for Astronomy Picture of the Day, optional)
NASA_API_KEY = env("NASA_API_KEY", default="DEMO_KEY")  # Use a demo key if not set

# AWS/S3 media storage settings.
# Django 4.2+ uses STORAGES; DEFAULT_FILE_STORAGE is ignored by Django 5.x.
# Set USE_S3=FALSE to force local media storage even if bucket env vars are present.
AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID", default="")
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY", default="")
AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME", default="")
AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME", default="eu-north-1")
AWS_S3_ENDPOINT_URL = env(
    "AWS_S3_ENDPOINT_URL",
    default=f"https://s3.{AWS_S3_REGION_NAME}.amazonaws.com",
)
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_FILE_OVERWRITE = False  # don't overwrite user uploaded files
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = env.bool("AWS_QUERYSTRING_AUTH", default=True)
AWS_S3_CUSTOM_DOMAIN = env("AWS_S3_CUSTOM_DOMAIN", default="")
AWS_LOCATION = env("AWS_LOCATION", default="")
USE_S3 = env.bool("USE_S3", default=bool(AWS_STORAGE_BUCKET_NAME))

STORAGES = {
    "default": {
        "BACKEND": (
            "storages.backends.s3boto3.S3Boto3Storage"
            if USE_S3
            else "django.core.files.storage.FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Compatibility for older Django versions and third-party packages that still read this setting.
DEFAULT_FILE_STORAGE = STORAGES["default"]["BACKEND"]


# Comma-separated host allowlist, e.g. "autumn.example.com,localhost".
# Defaults to "*" so existing deployments keep working; set it on the PaaS.
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["*"])

# Browser Web Push is deliberately optional.  A deployment can run all timer
# functionality without push credentials; the dispatcher will mark due work
# unavailable instead of retrying it forever.
PUSH_VAPID_PUBLIC_KEY = env("PUSH_VAPID_PUBLIC_KEY", default="").strip()
PUSH_VAPID_PRIVATE_KEY = env("PUSH_VAPID_PRIVATE_KEY", default="").strip()
PUSH_VAPID_SUBJECT = env("PUSH_VAPID_SUBJECT", default="").strip()
PUSH_WEBPUSH_TIMEOUT = env.float("PUSH_WEBPUSH_TIMEOUT", default=10.0)
PUSH_MAX_ATTEMPTS = env.int("PUSH_MAX_ATTEMPTS", default=5)
PUSH_RETRY_BASE_SECONDS = env.int("PUSH_RETRY_BASE_SECONDS", default=30)
PUSH_CLAIM_LEASE_SECONDS = env.int("PUSH_CLAIM_LEASE_SECONDS", default=120)
# Opt-in in-process dispatcher thread.  Off by default: the bounded
# ``dispatch_timer_reminders`` cron command stays the alternative delivery path.
RUN_REMINDER_DISPATCHER = env.bool("RUN_REMINDER_DISPATCHER", default=False)
PUSH_DISPATCH_INTERVAL_SECONDS = env.float("PUSH_DISPATCH_INTERVAL_SECONDS", default=15.0)
PUSH_ALLOWED_ENDPOINT_SUFFIXES = tuple(
    suffix.strip().lower().lstrip(".")
    for suffix in env.list(
        "PUSH_ALLOWED_ENDPOINT_SUFFIXES",
        default=[
            "fcm.googleapis.com",
            "push.services.mozilla.com",
            "notify.windows.com",
            "push.apple.com",
        ],
    )
    if suffix.strip()
)

# Single-user install: registration is closed unless explicitly enabled.
ALLOW_REGISTRATION = env.bool("ALLOW_REGISTRATION", default=False)

# Application definition

INSTALLED_APPS = [
    "core.apps.CoreConfig",
    "users.apps.UsersConfig",
    "llm_insights.apps.LlmInsightsConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",  # for JWT token authentication
    "drf_spectacular",
    "crispy_forms",
    "crispy_bootstrap4",
    "storages",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.github",
    "allauth.socialaccount.providers.google",
    "django_cleanup.apps.CleanupConfig",  # delete old files and images on file field and imagefield update/delete
]

CRISPY_TEMPLATE_PACK = "bootstrap4"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Autumn API v2",
    "VERSION": "2.0.0",
    "PREPROCESSING_HOOKS": ["core.api_v2.schema.v2_endpoints_only"],
}


AUTHENTICATION_BACKENDS = [
    "users.auth_backends.EmailOrUsernameModelBackend",  # use email or username to login
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # for serving static files in production
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "users.middleware.UserTimezoneMiddleware",
    "core.api_v2.middleware.V2ErrorEnvelopeMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=[
        "http://127.0.0.1:4173",
        "http://localhost:4173",
        "https://fingolfin7.github.io",
    ],
)
CORS_ALLOW_CREDENTIALS = env.bool("CORS_ALLOW_CREDENTIALS", default=True)
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=CORS_ALLOWED_ORIGINS)

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",  # was running into issues with PickleCache due to thread locking
        "LOCATION": "unique-snowflake",
    }
}

ROOT_URLCONF = "AutumnWeb.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "core/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.static_version",  # Custom context processor for static versioning
                "core.context_processors.active_context",  # Inject active context + user contexts
                "users.context_processors.auth_features",
            ],
        },
    },
]

WSGI_APPLICATION = "AutumnWeb.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Prefer a single DATABASE_URL in production, e.g.
#   postgres://USER:PASSWORD@HOST:5432/DBNAME
# Fallback to discrete env vars or finally SQLite for local/dev.
DATABASE_URL = env("DATABASE_URL", default="")

if DATABASE_URL:
    DATABASES = {"default": env.db("DATABASE_URL")}
else:
    POSTGRES_NAME = env("POSTGRES_DB", default="")
    POSTGRES_USER = env("POSTGRES_USER", default="")
    POSTGRES_PASSWORD = env("POSTGRES_PASSWORD", default="")
    POSTGRES_HOST = env("POSTGRES_HOST", default="")
    POSTGRES_PORT = env("POSTGRES_PORT", default="5432")

    if POSTGRES_NAME and POSTGRES_USER and POSTGRES_PASSWORD and POSTGRES_HOST:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": POSTGRES_NAME,
                "USER": POSTGRES_USER,
                "PASSWORD": POSTGRES_PASSWORD,
                "HOST": POSTGRES_HOST,
                "PORT": POSTGRES_PORT,
            }
        }
    else:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }

if os.environ.get("AUTUMN_CHZ_DB"):
    DATABASES["default"].setdefault("TEST", {})["NAME"] = os.environ["AUTUMN_CHZ_DB"]

# Keep DB connections open a bit (helps in production). Set to 0 to disable.
CONN_MAX_AGE = env.int("CONN_MAX_AGE", default=60)

# PostgreSQL server-side settings (optional). If you're using pgbouncer, you may want DISABLE_SERVER_SIDE_CURSORS=True
DISABLE_SERVER_SIDE_CURSORS = env.bool("DISABLE_SERVER_SIDE_CURSORS", default=False)

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Logging
#
# Render captures stdout/stderr and makes those streams searchable. Keep file
# logging as a local convenience, but do not make production diagnostics depend
# on an ephemeral filesystem.
LOG_LEVEL = env("LOG_LEVEL", default="INFO").upper()
ROOT_LOG_LEVEL = (
    LOG_LEVEL if LOG_LEVEL in {"WARNING", "ERROR", "CRITICAL"} else "WARNING"
)
LOG_TO_FILES = env.bool(
    "LOG_TO_FILES",
    default=not env.bool("RENDER", default=False),
)
LOG_DIR = BASE_DIR / "Logs"

LOG_HANDLERS = {
    "console": {
        "level": LOG_LEVEL,
        "class": "logging.StreamHandler",
        "stream": "ext://sys.stdout",
        "formatter": "structured",
    },
}
APP_LOG_HANDLERS = ["console"]
SIGNAL_LOG_HANDLERS = ["console"]
MODEL_LOG_HANDLERS = ["console"]

if LOG_TO_FILES:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    LOG_HANDLERS.update(
        {
            "main": {
                "level": LOG_LEVEL,
                "class": "concurrent_log_handler.ConcurrentRotatingFileHandler",
                "filename": LOG_DIR / "main.log",
                "maxBytes": 0.5 * 1024 * 1024,
                "backupCount": 5,
                "formatter": "structured",
            },
            "signals": {
                "level": LOG_LEVEL,
                "class": "concurrent_log_handler.ConcurrentRotatingFileHandler",
                "filename": LOG_DIR / "signals.log",
                "maxBytes": 0.5 * 1024 * 1024,
                "backupCount": 5,
                "formatter": "structured",
            },
            "models": {
                "level": LOG_LEVEL,
                "class": "concurrent_log_handler.ConcurrentRotatingFileHandler",
                "filename": LOG_DIR / "models.log",
                "maxBytes": 0.5 * 1024 * 1024,
                "backupCount": 5,
                "formatter": "structured",
            },
        }
    )
    APP_LOG_HANDLERS.append("main")
    SIGNAL_LOG_HANDLERS.append("signals")
    MODEL_LOG_HANDLERS.append("models")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "structured": {
            "format": (
                "timestamp=%(asctime)s level=%(levelname)s logger=%(name)s "
                "module=%(module)s message=%(message)s"
            ),
            "datefmt": "%Y-%m-%dT%H:%M:%S%z",
        },
    },
    "handlers": LOG_HANDLERS,
    "root": {
        "handlers": ["console"],
        # Keep unexpected third-party chatter out of production while still
        # surfacing warnings and errors from libraries without dedicated rules.
        "level": ROOT_LOG_LEVEL,
    },
    "loggers": {
        "AutumnWeb": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "core": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "users": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "llm_insights": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "main": {
            "handlers": APP_LOG_HANDLERS,
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "signals": {
            "handlers": SIGNAL_LOG_HANDLERS,
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "models": {
            "handlers": MODEL_LOG_HANDLERS,
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Prague"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static" if not DEBUG else "staticfiles")

MEDIA_ROOT = env("MEDIA_ROOT", default=os.path.join(BASE_DIR, "media"))

MEDIA_URL = "/media/"

# If True, the Django app will serve user-uploaded media itself (even when DEBUG=False).
# Useful for small deployments on PaaS with a persistent disk.
SERVE_MEDIA = env.bool("SERVE_MEDIA", default=False)

# Static Versioning
STATIC_VERSION_CACHE_TIMEOUT = {
    "debug": 0,  # always refresh in debug mode
    "production": 3600,  # 1 hour
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "home"
LOGIN_URL = "login"

# Optional social authentication. Provider credentials live in the deployment
# environment rather than the database, so database backups do not contain
# OAuth client secrets.
GOOGLE_OAUTH_CLIENT_ID = env("GOOGLE_OAUTH_CLIENT_ID", default="")
GOOGLE_OAUTH_CLIENT_SECRET = env("GOOGLE_OAUTH_CLIENT_SECRET", default="")
GITHUB_OAUTH_CLIENT_ID = env("GITHUB_OAUTH_CLIENT_ID", default="")
GITHUB_OAUTH_CLIENT_SECRET = env("GITHUB_OAUTH_CLIENT_SECRET", default="")

GOOGLE_AUTH_ENABLED = bool(GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_CLIENT_SECRET)
GITHUB_AUTH_ENABLED = bool(GITHUB_OAUTH_CLIENT_ID and GITHUB_OAUTH_CLIENT_SECRET)

ACCOUNT_ADAPTER = "users.adapters.AutumnAccountAdapter"
SOCIALACCOUNT_ADAPTER = "users.adapters.AutumnSocialAccountAdapter"
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_LOGIN_ON_GET = False
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_STORE_TOKENS = False
ACCOUNT_EMAIL_VERIFICATION = "none"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["openid", "profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "OAUTH_PKCE_ENABLED": True,
    },
    # This is the minimum scope needed when a GitHub user keeps their primary
    # email private; no repository or organization access is requested.
    "github": {"SCOPE": ["user:email"]},
}
if GOOGLE_AUTH_ENABLED:
    SOCIALACCOUNT_PROVIDERS["google"]["APP"] = {
        "client_id": GOOGLE_OAUTH_CLIENT_ID,
        "secret": GOOGLE_OAUTH_CLIENT_SECRET,
        "key": "",
    }
if GITHUB_AUTH_ENABLED:
    SOCIALACCOUNT_PROVIDERS["github"]["APP"] = {
        "client_id": GITHUB_OAUTH_CLIENT_ID,
        "secret": GITHUB_OAUTH_CLIENT_SECRET,
        "key": "",
    }

# AUDIT Settings
RUN_AUDIT_SCHEDULER = env.bool(
    "RUN_AUDIT_SCHEDULER", False
)  # convert the string to a boolean
AUDIT_PERIOD = env.int("AUDIT_PERIOD")

# Test-only overrides. PBKDF2's slowness is a security feature in production but
# dominates test runtime (~1.4s per test for create_user/login), so use MD5 there.
import sys

TESTING = len(sys.argv) > 1 and sys.argv[1] == "test"
if TESTING:
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]
