"""
Django settings for AutumnWeb project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from concurrent_log_handler import ConcurrentRotatingFileHandler
import logging.handlers
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
if Path('.env').exists():
    environ.Env.read_env(overwrite=True) # force the environment variables to be read from the .env file
elif Path(BASE_DIR / ".env").exists():
    environ.Env.read_env(BASE_DIR / ".env", overwrite=True)  # for production deployment where .env is in the BASE_DIR

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

# Gemini API Key
GEMINI_API_KEY = env('GEMINI_API_KEY')
# NASA API Key (for Astronomy Picture of the Day, optional)
NASA_API_KEY = env('NASA_API_KEY', default='DEMO_KEY')  # Use a demo key if not set


ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'core.apps.CoreConfig',
    'users.apps.UsersConfig',
    'llm_insights.apps.LlmInsightsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'rest_framework',
    'rest_framework.authtoken',  # for JWT token authentication
    'crispy_forms',
    'crispy_bootstrap4',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup.apps.CleanupConfig',  # delete old files and images on file field and imagefield update/delete
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
}


AUTHENTICATION_BACKENDS = [
    'users.auth_backends.EmailOrUsernameModelBackend', # use email or username to login
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # for serving static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache', # was running into issues with PickleCache due to thread locking
        'LOCATION': 'unique-snowflake',
    }
}

ROOT_URLCONF = 'AutumnWeb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core/templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.static_version',  # Custom context processor for static versioning
                'core.context_processors.active_context',  # Inject active context + user contexts
            ],
        },
    },
]

WSGI_APPLICATION = 'AutumnWeb.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Prefer a single DATABASE_URL in production, e.g.
#   postgres://USER:PASSWORD@HOST:5432/DBNAME
# Fallback to discrete env vars or finally SQLite for local/dev.
DATABASE_URL = env('DATABASE_URL', default='')

if DATABASE_URL:
    DATABASES = {
        'default': env.db('DATABASE_URL')
    }
else:
    POSTGRES_NAME = env('POSTGRES_DB', default='')
    POSTGRES_USER = env('POSTGRES_USER', default='')
    POSTGRES_PASSWORD = env('POSTGRES_PASSWORD', default='')
    POSTGRES_HOST = env('POSTGRES_HOST', default='')
    POSTGRES_PORT = env('POSTGRES_PORT', default='5432')

    if POSTGRES_NAME and POSTGRES_USER and POSTGRES_PASSWORD and POSTGRES_HOST:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': POSTGRES_NAME,
                'USER': POSTGRES_USER,
                'PASSWORD': POSTGRES_PASSWORD,
                'HOST': POSTGRES_HOST,
                'PORT': POSTGRES_PORT,
            }
        }
    else:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }

# Keep DB connections open a bit (helps in production). Set to 0 to disable.
CONN_MAX_AGE = env.int('CONN_MAX_AGE', default=60)

# PostgreSQL server-side settings (optional). If you're using pgbouncer, you may want DISABLE_SERVER_SIDE_CURSORS=True
DISABLE_SERVER_SIDE_CURSORS = env.bool('DISABLE_SERVER_SIDE_CURSORS', default=False)

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Logging
LOG_DIR = os.path.join(BASE_DIR, 'Logs')

if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[%(asctime)s] [%(levelname)s] [%(module)s] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[%(asctime)s] [%(module)s] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'main': {
            'level': 'INFO',
            'class': 'concurrent_log_handler.ConcurrentRotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'main.log'),
            'maxBytes': 0.5 * 1024 * 1024,  # Rotate when the file reaches half a megabyte
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'signals': {
            'level': 'INFO',
            'class': 'concurrent_log_handler.ConcurrentRotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'signals.log'),
            'maxBytes': 0.5 * 1024 * 1024,  # Rotate when the file reaches half a megabyte
            'backupCount': 5,
            'formatter': 'simple',
        },
        'models': {
            'level': 'INFO',
            'class': 'concurrent_log_handler.ConcurrentRotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'models.log'),
            'maxBytes': 0.5 * 1024 * 1024,  # Rotate when the file reaches half a megabyte
            'backupCount': 5,
            'formatter': 'simple',
        },
    },
    'loggers': {
        'main': {
            'handlers': ['main'],
            'level': 'INFO',
            'propagate': False,
        },
        'signals': {
            'handlers': ['signals'],
            'level': 'INFO',
            'propagate': False,
        },
        'models': {
            'handlers': ['models'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Prague'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static' if not DEBUG else 'staticfiles')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media') if DEBUG else '/media'
MEDIA_URL = '/media/'

# Static Versioning
STATIC_VERSION_CACHE_TIMEOUT = {
    'debug': 0,     # always refresh in debug mode
    'production': 3600  # 1 hour
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'login'

# AUDIT Settings
RUN_AUDIT_SCHEDULER = env.bool('RUN_AUDIT_SCHEDULER', False) # convert the string to a boolean
AUDIT_PERIOD = env.int('AUDIT_PERIOD')
