# Generated by Django 4.2 on 2023-09-04 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=250)),
                ('last_updated', models.DateField(auto_now=True)),
                ('total_time', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=250)),
                ('last_updated', models.DateField(auto_now=True)),
                ('total_time', models.FloatField(default=0.0)),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_created=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('duration', models.FloatField(default=0.0)),
                ('note', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_project', to='core.projects')),
                ('subprojects', models.ManyToManyField(related_name='session_subprojects', to='core.subprojects')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveTimers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_created=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_project', to='core.projects')),
                ('subprojects', models.ManyToManyField(related_name='active_subprojects', to='core.subprojects')),
            ],
        ),
    ]
