# Generated by Django 4.2 on 2024-01-26 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='duration',
        ),
        migrations.AddField(
            model_name='sessions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='last_updated',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=25),
        ),
        migrations.AlterField(
            model_name='projects',
            name='total_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projects'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='subprojects',
            field=models.ManyToManyField(to='core.subprojects'),
        ),
        migrations.AlterField(
            model_name='subprojects',
            name='last_updated',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subprojects',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subprojects',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subprojects',
            name='total_time',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='ActiveTimers',
        ),
    ]
