# Generated by Django 4.2 on 2024-01-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_projects_description_remove_sessions_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subprojects',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
