# Generated by Django 4.2 on 2024-01-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_projects_name_alter_subprojects_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='total_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subprojects',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subprojects',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subprojects',
            name='total_time',
            field=models.FloatField(default=0.0),
        ),
    ]
