# Generated by Django 4.2 on 2024-05-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_projects_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='sessions',
            options={'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterModelOptions(
            name='subprojects',
            options={'verbose_name_plural': 'SubProjects'},
        ),
        migrations.AlterField(
            model_name='subprojects',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
