# Generated by Django 4.2 on 2024-05-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_projects_options_alter_sessions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
