# Generated by Django 4.2 on 2024-06-13 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sessions_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['name'], 'verbose_name_plural': 'Projects'},
        ),
    ]
