# Generated by Django 4.2 on 2024-06-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_sessions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessions',
            options={'ordering': ['-start_time'], 'verbose_name_plural': 'Sessions'},
        ),
    ]
