# Generated by Django 4.2 on 2024-06-16 21:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_sessions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.projects'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='subprojects',
            field=models.ManyToManyField(related_name='sessions', to='core.subprojects'),
        ),
        migrations.AlterField(
            model_name='subprojects',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subprojects',
            name='parent_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprojects', to='core.projects'),
        ),
        migrations.AlterField(
            model_name='subprojects',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
