# Generated by Django 4.2 on 2024-06-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_projects_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
