# Generated by Django 4.2 on 2024-06-17 00:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_sessions_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
