# Generated by Django 4.2 on 2024-07-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_projects_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subprojects',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
