# Generated by Django 4.2 on 2024-07-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_projects_description_subprojects_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessions',
            options={'ordering': ['-end_time'], 'verbose_name_plural': 'Sessions'},
        ),
    ]
