# Generated by Django 4.2 on 2024-07-26 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_sessions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprojects',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
