# Generated by Django 4.2.14 on 2024-09-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_subprojects_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('complete', 'Complete')], default='active', max_length=25),
        ),
    ]
