# Generated by Django 4.2.15 on 2024-12-05 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_sessions_core_sessio_is_acti_801316_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='pre_save_duration',
        ),
    ]
