# Generated by Django 4.2.15 on 2024-12-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_sessions_pre_save_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='pre_save_duration',
            field=models.FloatField(default=0.0),
        ),
    ]
