# Generated by Django 4.2.15 on 2024-12-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_sessions_pre_save_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='pre_save_duration',
        ),
    ]
