# Generated by Django 5.2 on 2025-11-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_sessions_pre_save_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('complete', 'Complete'), ('archived', 'Archived')], default='active', max_length=25),
        ),
    ]
