# Generated by Django 5.2 on 2026-02-02 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_enforce_general_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment_type', models.CharField(choices=[('time', 'Time-based'), ('sessions', 'Session-based')], default='time', max_length=10)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='weekly', max_length=15)),
                ('target', models.PositiveIntegerField(help_text='Minutes (time) or count (sessions)')),
                ('balance', models.IntegerField(default=0)),
                ('max_balance', models.PositiveIntegerField(default=600, help_text='Maximum balance cap (10 hours default)')),
                ('min_balance', models.IntegerField(default=-600, help_text='Minimum balance cap (10 hours deficit default)')),
                ('banking_enabled', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_reconciled', models.DateTimeField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commitment', to='core.projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commitment',
                'verbose_name_plural': 'Commitments',
            },
        ),
    ]
