# Generated by Django 5.2.11 on 2026-02-23 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_sessions_crosses_dst_transition"),
    ]

    operations = [
        migrations.AddField(
            model_name="commitment",
            name="aggregation_type",
            field=models.CharField(
                choices=[
                    ("project", "Project"),
                    ("subproject", "Subproject"),
                    ("context", "Context"),
                    ("tag", "Tag"),
                ],
                default="project",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="commitment",
            name="context",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commitment",
                to="core.context",
            ),
        ),
        migrations.AddField(
            model_name="commitment",
            name="subproject",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commitment",
                to="core.subprojects",
            ),
        ),
        migrations.AddField(
            model_name="commitment",
            name="tag",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commitment",
                to="core.tag",
            ),
        ),
        migrations.AlterField(
            model_name="commitment",
            name="project",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commitment",
                to="core.projects",
            ),
        ),
    ]
