# Generated by Django 5.2 on 2026-03-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_commitment_aggregation_type_commitment_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='exclude_contexts',
            field=models.ManyToManyField(blank=True, related_name='commitments_excluding', to='core.context'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='exclude_projects',
            field=models.ManyToManyField(blank=True, related_name='commitments_excluding', to='core.projects'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='exclude_subprojects',
            field=models.ManyToManyField(blank=True, related_name='commitments_excluding', to='core.subprojects'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='exclude_tags',
            field=models.ManyToManyField(blank=True, related_name='commitments_excluding', to='core.tag'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='include_contexts',
            field=models.ManyToManyField(blank=True, related_name='commitments_including', to='core.context'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='include_projects',
            field=models.ManyToManyField(blank=True, related_name='commitments_including', to='core.projects'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='include_subprojects',
            field=models.ManyToManyField(blank=True, related_name='commitments_including', to='core.subprojects'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='include_tags',
            field=models.ManyToManyField(blank=True, related_name='commitments_including', to='core.tag'),
        ),
    ]
