# Generated by Django 5.2 on 2026-03-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_commitment_exclude_contexts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='aggregation_type',
            field=models.CharField(choices=[('context', 'Context'), ('tag', 'Tag'), ('project', 'Project'), ('subproject', 'Subproject')], default='project', max_length=20),
        ),
    ]
