# Generated by Django 5.2 on 2026-03-02 23:11

import django.utils.timezone
from django.db import migrations, models


def backfill_start_date_from_created_at(apps, schema_editor):
    Commitment = apps.get_model("core", "Commitment")
    for c in Commitment.objects.filter(start_date__isnull=True):
        if c.created_at is not None:
            c.start_date = django.utils.timezone.localtime(c.created_at).date()
        else:
            c.start_date = django.utils.timezone.localdate()
        c.save(update_fields=["start_date"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_commitment_aggregation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_start_date_from_created_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='commitment',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Date when commitment period calculations begin'),
        ),
    ]
