# Generated by Codex on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_commitment_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessions",
            name="auto_stop_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
