# Generated by Django 5.2 on 2026-07-12 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_sessions_auto_stop_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sessions',
            index=models.Index(fields=['user', 'is_active', 'end_time'], name='core_sessio_user_id_51a485_idx'),
        ),
    ]
