# Generated by Django 5.2 on 2026-07-16 05:28

import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_session_uuids(apps, schema_editor):
    Sessions = apps.get_model('core', 'Sessions')
    for session in Sessions.objects.filter(uuid__isnull=True).iterator():
        session.uuid = uuid.uuid4()
        session.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_floor_session_instants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add WITHOUT a default: AddField evaluates a callable default once and
        # would stamp every existing row with the same UUID, breaking the
        # unique constraint below. Existing rows stay NULL here.
        migrations.AddField(
            model_name='sessions',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        # Backfill each existing row with its own UUID.
        migrations.RunPython(
            backfill_session_uuids,
            reverse_code=migrations.RunPython.noop,
        ),
        # Attach the app-level default for new rows (no data change).
        migrations.AlterField(
            model_name='sessions',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='sessions',
            constraint=models.UniqueConstraint(fields=('user', 'uuid'), name='unique_session_uuid_per_user'),
        ),
    ]
