# Generated by Django 5.2 on 2026-07-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_sessions_weighted_read_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='version',
            field=models.IntegerField(db_default=1, default=1),
        ),
    ]
