# Generated by Django 5.2 on 2026-07-16 12:37

import django.db.models.deletion
from django.utils import timezone
from django.db import migrations, models


FILTER_FIELDS = (
    'include_projects',
    'exclude_projects',
    'include_subprojects',
    'exclude_subprojects',
    'include_contexts',
    'exclude_contexts',
    'include_tags',
    'exclude_tags',
)


def snapshot_existing_commitments(apps, schema_editor):
    Commitment = apps.get_model('core', 'Commitment')
    CommitmentAdjustment = apps.get_model('core', 'CommitmentAdjustment')
    CommitmentRevision = apps.get_model('core', 'CommitmentRevision')
    cutover = timezone.now()

    for commitment in Commitment.objects.all().iterator():
        target = getattr(commitment, commitment.aggregation_type, None)
        filters = {}
        for field in FILTER_FIELDS:
            filters[field] = [
                {'id': obj.pk, 'name': obj.name}
                for obj in getattr(commitment, field).all().order_by('pk')
            ]

        CommitmentRevision.objects.create(
            commitment_id=commitment.pk,
            generation=1,
            effective_from_instant=cutover,
            status='active',
            aggregation_type=commitment.aggregation_type,
            target_id=target.pk if target is not None else None,
            target_name=target.name if target is not None else '',
            filters_snapshot=filters,
            commitment_type=commitment.commitment_type,
            cadence=commitment.period,
            target_value=commitment.target,
            banking_enabled=commitment.banking_enabled,
            max_balance=commitment.max_balance,
            min_balance=commitment.min_balance,
            start_date=commitment.start_date,
            timezone='Europe/Prague',
        )
        CommitmentAdjustment.objects.create(
            commitment_id=commitment.pk,
            seq=1,
            kind='opening',
            amount=commitment.balance,
            effective_at=cutover,
            reason='Migration cutover opening balance',
        )
        Commitment.objects.filter(pk=commitment.pk).update(
            generation=1,
            ledger_start_at=cutover,
            needs_recompute=False,
            version=1,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_sessions_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='generation',
            field=models.IntegerField(db_default=1, default=1),
        ),
        migrations.AddField(
            model_name='commitment',
            name='ledger_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='needs_recompute',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='commitment',
            name='version',
            field=models.IntegerField(db_default=1, default=1),
        ),
        migrations.CreateModel(
            name='CommitmentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.IntegerField(db_default=1, default=1)),
                ('effective_from_instant', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], max_length=10)),
                ('aggregation_type', models.CharField(choices=[('context', 'Context'), ('tag', 'Tag'), ('project', 'Project'), ('subproject', 'Subproject')], max_length=20)),
                ('target_id', models.BigIntegerField(blank=True, null=True)),
                ('target_name', models.CharField(db_default='', default='', max_length=255)),
                ('filters_snapshot', models.JSONField(default=dict)),
                ('commitment_type', models.CharField(choices=[('time', 'Time-based'), ('sessions', 'Session-based')], max_length=10)),
                ('cadence', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=15)),
                ('target_value', models.PositiveIntegerField()),
                ('banking_enabled', models.BooleanField(db_default=True, default=True)),
                ('max_balance', models.IntegerField(db_default=600, default=600)),
                ('min_balance', models.IntegerField(db_default=-600, default=-600)),
                ('start_date', models.DateField()),
                ('timezone', models.CharField(db_default='Europe/Prague', default='Europe/Prague', max_length=64)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.commitment')),
            ],
        ),
        migrations.CreateModel(
            name='CommitmentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.IntegerField(db_default=1, default=1)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('accrued_numerator', models.BigIntegerField(db_default=0, default=0)),
                ('session_count', models.IntegerField(db_default=0, default=0)),
                ('carryover_in', models.IntegerField(db_default=0, default=0)),
                ('balance_out', models.IntegerField(db_default=0, default=0)),
                ('closed_at', models.DateTimeField()),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_rows', to='core.commitment')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='period_rows', to='core.commitmentrevision')),
            ],
        ),
        migrations.CreateModel(
            name='CommitmentAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('kind', models.CharField(choices=[('opening', 'Opening'), ('restart_carry', 'Restart carry'), ('manual', 'Manual')], max_length=20)),
                ('amount', models.IntegerField()),
                ('effective_at', models.DateTimeField()),
                ('reason', models.TextField(db_default='', default='')),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='core.commitment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('commitment', 'seq'), name='unique_commitment_adjustment_seq')],
            },
        ),
        migrations.AddConstraint(
            model_name='commitmentrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('commitment',), name='one_pending_revision_per_commitment'),
        ),
        migrations.AddConstraint(
            model_name='commitmentperiod',
            constraint=models.UniqueConstraint(fields=('commitment', 'generation', 'period_start'), name='unique_commitment_generation_period_start'),
        ),
        migrations.RunPython(
            snapshot_existing_commitments,
            migrations.RunPython.noop,
        ),
    ]
