# Generated by Django 5.2 on 2026-07-17 07:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_commitment_replay_ledger'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sessions',
            name='core_sessio_is_acti_801316_idx',
        ),
        migrations.RemoveIndex(
            model_name='sessions',
            name='core_sessio_user_id_51a485_idx',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='total_time',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='crosses_dst_transition',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subprojects',
            name='total_time',
        ),
        migrations.AlterField(
            model_name='sessions',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
