# Generated by Django 5.2 on 2026-07-17 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_sessions_core_sessio_is_acti_801316_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sessions',
            name='core_sessio_user_id_509018_idx',
        ),
        migrations.AlterField(
            model_name='sessionsubproject',
            name='session',
            field=models.ForeignKey(db_column='sessions_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='subproject_links', to='core.sessions'),
        ),
    ]
