# Generated by Django 5.2.16 on 2026-08-30 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_subproject_to_subprojects(apps, schema_editor):
    """Carry each single-subproject schedule into the new many-to-many table.

    This runs while the old ``subproject`` column still exists, so no targeting
    information is lost when the column is dropped in the next operation.
    """

    ScheduledReminder = apps.get_model("core", "ScheduledReminder")
    through = ScheduledReminder.subprojects.through
    links = [
        through(scheduledreminder_id=reminder_id, subprojects_id=subproject_id)
        for reminder_id, subproject_id in ScheduledReminder.objects.filter(
            subproject__isnull=False
        ).values_list("pk", "subproject_id")
    ]
    if links:
        through.objects.bulk_create(links, ignore_conflicts=True)


def noop(apps, schema_editor):
    """Reversing only drops the M2M table; nothing to restore beforehand."""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_commitment_notifications_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledreminder',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reminders', to='core.context'),
        ),
        migrations.AddField(
            model_name='scheduledreminder',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reminders', to='core.tag'),
        ),
        migrations.AddField(
            model_name='scheduledreminder',
            name='subprojects',
            field=models.ManyToManyField(blank=True, related_name='scheduled_reminders', to='core.subprojects'),
        ),
        migrations.AlterField(
            model_name='scheduledreminder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reminders', to='core.projects'),
        ),
        migrations.RunPython(copy_subproject_to_subprojects, noop),
        migrations.RemoveField(
            model_name='scheduledreminder',
            name='subproject',
        ),
        migrations.AddConstraint(
            model_name='scheduledreminder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('context__isnull', True), ('project__isnull', False), ('tag__isnull', True)), models.Q(('context__isnull', False), ('project__isnull', True), ('tag__isnull', True)), models.Q(('context__isnull', True), ('project__isnull', True), ('tag__isnull', False)), _connector='OR'), name='schedrem_target_exactly_one'),
        ),
    ]
