# Generated by Django 5.2.16 on 2026-09-21 22:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_notificationevent_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('provider', models.CharField(max_length=16)),
                ('event', models.CharField(default='attempt', max_length=16)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('effort', models.CharField(blank=True, max_length=16)),
                ('auth_route', models.CharField(blank=True, max_length=16)),
                ('success', models.BooleanField(default=False)),
                ('error_category', models.CharField(blank=True, max_length=80)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveBigIntegerField(null=True)),
                ('cached_input_tokens', models.PositiveBigIntegerField(null=True)),
                ('cache_write_tokens', models.PositiveBigIntegerField(null=True)),
                ('output_tokens', models.PositiveBigIntegerField(null=True)),
                ('reasoning_tokens', models.PositiveBigIntegerField(null=True)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('pricing', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=16)),
                ('scope', models.CharField(max_length=100)),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('result', models.JSONField(null=True)),
                ('generated_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_token', models.CharField(blank=True, max_length=36)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'provider', 'scope'), name='unique_recommendation_scope')],
            },
        ),
    ]
