# Generated by Django 5.2.16 on 2026-10-06 19:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_mcp_grants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPAccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='mcpgrant',
            name='oauth_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autumn_grants', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
        migrations.AlterField(
            model_name='mcpgrant',
            name='token_digest',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='mcpgrant',
            constraint=models.UniqueConstraint(fields=('owner', 'oauth_application'), name='mcp_owner_application_unique'),
        ),
        migrations.AddField(
            model_name='mcpaccountlink',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_account_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mcpaccountlink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_linked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='mcpaccountlink',
            constraint=models.UniqueConstraint(fields=('owner', 'user'), name='mcp_owner_link_unique'),
        ),
    ]
