# Generated by Django 5.2 on 2026-01-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmchat',
            name='filters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
