# urls.py
from django.urls import path
from core.views import (
    ProjectsListView,
    TimerListView,
    start_timer,
    stop_timer,
    restart_timer,
    remove_timer,
    CreateProjectView,
    CreateSubProjectView,
    UpdateProjectView,
    UpdateSubProjectView,
    DeleteProjectView,
    DeleteSubProjectView,
    SessionsListView,
    update_session,
    DeleteSessionView,
    ChartsView,
    import_view,
    import_stream,
    export_view,
    merge_projects,
    merge_subprojects,
    set_active_context,
    manage_contexts,
    manage_tags,
    UpdateContextView,
    DeleteContextView,
    UpdateTagView,
    DeleteTagView,
)
from core.api import (
    # new compact endpoints
    timer_start,
    timer_stop,
    timer_status,
    timer_restart,
    timer_delete,
    track_session,
    projects_list_grouped,
    projects_list_flat,
    subprojects_list,
    totals,
    rename_entity,
    project_delete_body,
    log_activity,
    search_sessions,
    mark_project,
    export_json_api,
    edit_session,
    # existing (migrated)
    create_project,
    list_projects,
    tally_by_sessions,
    tally_by_subprojects,
    tally_by_context,
    tally_by_status,
    tally_by_tags,
    hierarchy_data,
    projects_with_stats,
    search_projects,
    get_project,
    delete_project,
    create_subproject,
    list_subprojects,
    search_subprojects,
    delete_subproject,
    start_session,
    restart_session,
    end_session,
    log_session,
    delete_session,
    list_sessions,
    list_active_sessions,
    merge_projects_api,
    merge_subprojects_api,
    contexts_list,
    tags_list,
    me,
    audit,
)

urlpatterns = [
    # pages
    path("", ProjectsListView.as_view(), name="home"),
    path("projects/", ProjectsListView.as_view(), name="projects"),
    path("timers/", TimerListView.as_view(), name="timers"),
    path("start_timer/", start_timer, name="start_timer"),
    path("stop_timer/<int:session_id>/", stop_timer, name="stop_timer"),
    path("restart_timer/<int:session_id>/", restart_timer, name="restart_timer"),
    path("remove_timer/<int:session_id>/", remove_timer, name="remove_timer"),
    path("create_subproject/", CreateProjectView.as_view(), name="create_project"),
    path(
        "create_subproject/<int:pk>/",
        CreateSubProjectView.as_view(),
        name="create_subproject",
    ),
    path(
        "update_project/<int:pk>/", UpdateProjectView.as_view(), name="update_project"
    ),
    path(
        "update_subproject/<int:pk>/",
        UpdateSubProjectView.as_view(),
        name="update_subproject",
    ),
    path(
        "delete_project/<int:pk>/", DeleteProjectView.as_view(), name="delete_project"
    ),
    path(
        "delete_subproject/<int:pk>/",
        DeleteSubProjectView.as_view(),
        name="delete_subproject",
    ),
    path("sessions/", SessionsListView.as_view(), name="sessions"),
    path("update_session/<int:session_id>/", update_session, name="update_session"),
    path(
        "delete_session/<int:session_id>/",
        DeleteSessionView.as_view(),
        name="delete_session",
    ),
    path("charts/", ChartsView, name="charts"),
    path("export/", export_view, name="export"),
    path("import/", import_view, name="import"),
    path("import/stream/", import_stream, name="import_stream"),
    path("merge_projects/", merge_projects, name="merge_projects"),
    path(
        "merge_subprojects/<int:project_id>/",
        merge_subprojects,
        name="merge_subprojects",
    ),
    path("contexts/", manage_contexts, name="contexts"),
    path("tags/", manage_tags, name="tags"),
    path("set-context/", set_active_context, name="set_active_context"),
    # context/tag update/delete
    path(
        "update_context/<int:pk>/", UpdateContextView.as_view(), name="update_context"
    ),
    path(
        "delete_context/<int:pk>/", DeleteContextView.as_view(), name="delete_context"
    ),
    path("update_tag/<int:pk>/", UpdateTagView.as_view(), name="update_tag"),
    path("delete_tag/<int:pk>/", DeleteTagView.as_view(), name="delete_tag"),
    # migrated API
    path("api/create_project/", create_project, name="api_create_project"),
    path("api/list_projects/", list_projects, name="api_list_projects"),
    path("api/tally_by_sessions/", tally_by_sessions, name="api_tally_by_sessions"),
    path(
        "api/tally_by_subprojects/",
        tally_by_subprojects,
        name="api_tally_by_subprojects",
    ),
    path(
        "api/tally_by_context/",
        tally_by_context,
        name="api_tally_by_context",
    ),
    path(
        "api/tally_by_status/",
        tally_by_status,
        name="api_tally_by_status",
    ),
    path(
        "api/tally_by_tags/",
        tally_by_tags,
        name="api_tally_by_tags",
    ),
    path(
        "api/hierarchy/",
        hierarchy_data,
        name="api_hierarchy",
    ),
    path(
        "api/projects_with_stats/",
        projects_with_stats,
        name="api_projects_with_stats",
    ),
    path("api/search_projects/", search_projects, name="api_search_projects"),
    path("api/get_project/<str:project_name>/", get_project, name="api_get_project"),
    path(
        "api/delete_project/<str:project_name>/",
        delete_project,
        name="api_delete_project",
    ),
    path("api/create_subproject/", create_subproject, name="api_create_subproject"),
    path(
        "api/list_subprojects/<str:project_name>/",
        list_subprojects,
        name="api_list_subprojects",
    ),
    path("api/list_subprojects/", list_subprojects, name="api_list_subprojects_param"),
    path("api/search_subprojects/", search_subprojects, name="api_search_subprojects"),
    path(
        "api/delete_subproject/<str:project_name>/<str:subproject_name>/",
        delete_subproject,
        name="api_delete_subproject",
    ),
    path("api/start_session/", start_session, name="api_start_session"),
    path("api/restart_session/", restart_session, name="api_restart_session"),
    path("api/end_session/", end_session, name="api_end_session"),
    path("api/log_session/", log_session, name="api_log_session"),
    path("api/sessions/search/", search_sessions, name="api_sessions_search"),
    path(
        "api/delete_session/<int:session_id>/",
        delete_session,
        name="api_delete_session",
    ),
    path("api/list_sessions/", list_sessions, name="api_list_sessions"),
    path(
        "api/list_active_sessions/",
        list_active_sessions,
        name="api_list_active_sessions",
    ),
    path("api/merge_projects/", merge_projects_api, name="api_merge_projects"),
    path("api/merge_subprojects/", merge_subprojects_api, name="api_merge_subprojects"),
    # new compact endpoints for MCP/LLMs
    path("api/timer/start/", timer_start, name="api_timer_start"),
    path("api/timer/stop/", timer_stop, name="api_timer_stop"),
    path("api/timer/status/", timer_status, name="api_timer_status"),
    path("api/timer/restart/", timer_restart, name="api_timer_restart"),
    path("api/timer/delete/", timer_delete, name="api_timer_delete"),
    path("api/track/", track_session, name="api_track"),
    path("api/projects/grouped/", projects_list_grouped, name="api_projects_grouped"),
    path("api/projects/", projects_list_flat, name="api_projects_flat"),
    path("api/subprojects/", subprojects_list, name="api_subprojects_list"),
    path("api/session/<int:session_id>/", edit_session, name="api_edit_session"),
    path("api/totals/", totals, name="api_totals"),
    path("api/rename/", rename_entity, name="api_rename"),
    path("api/project/delete/", project_delete_body, name="api_project_delete_body"),
    path("api/log/", log_activity, name="api_log"),
    path("api/mark/", mark_project, name="api_mark_project"),
    path("api/export/", export_json_api, name="api_export_json"),
    # discovery endpoints (contexts/tags)
    path("api/contexts/", contexts_list, name="api_contexts_list"),
    path("api/tags/", tags_list, name="api_tags_list"),
    path("api/me/", me, name="api_me"),
    path("api/audit/", audit, name="api_audit"),
]
